//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResCommon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResCommon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResCommon", typeof(ResCommon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopiere Token ....
        /// </summary>
        public static string BusyCopyToken {
            get {
                return ResourceManager.GetString("BusyCopyToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösche Token ....
        /// </summary>
        public static string BusyDeleteToken {
            get {
                return ResourceManager.GetString("BusyDeleteToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sichere Token ....
        /// </summary>
        public static string BusySaveToken {
            get {
                return ResourceManager.GetString("BusySaveToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuer Token.
        /// </summary>
        public static string CmdAddToken {
            get {
                return ResourceManager.GetString("CmdAddToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Einstellungen.
        /// </summary>
        public static string CmdAdminSettings {
            get {
                return ResourceManager.GetString("CmdAdminSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zurück.
        /// </summary>
        public static string CmdBack {
            get {
                return ResourceManager.GetString("CmdBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Abbrechen.
        /// </summary>
        public static string CmdCancel {
            get {
                return ResourceManager.GetString("CmdCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string CmdChat {
            get {
                return ResourceManager.GetString("CmdChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fertig.
        /// </summary>
        public static string CmdEditFinish {
            get {
                return ResourceManager.GetString("CmdEditFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiterentwicklung.
        /// </summary>
        public static string CmdFutureDevelopment {
            get {
                return ResourceManager.GetString("CmdFutureDevelopment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Übersicht.
        /// </summary>
        public static string CmdHome {
            get {
                return ResourceManager.GetString("CmdHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string CmdInfo {
            get {
                return ResourceManager.GetString("CmdInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string CmdLogin {
            get {
                return ResourceManager.GetString("CmdLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mehr.
        /// </summary>
        public static string CmdMore {
            get {
                return ResourceManager.GetString("CmdMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mehr Infos.
        /// </summary>
        public static string CmdMoreToolTip {
            get {
                return ResourceManager.GetString("CmdMoreToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nein.
        /// </summary>
        public static string CmdNo {
            get {
                return ResourceManager.GetString("CmdNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string CmdOk {
            get {
                return ResourceManager.GetString("CmdOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User+.
        /// </summary>
        public static string CmdOrganization {
            get {
                return ResourceManager.GetString("CmdOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beanstandungen.
        /// </summary>
        public static string CmdReportOverview {
            get {
                return ResourceManager.GetString("CmdReportOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern.
        /// </summary>
        public static string CmdSave {
            get {
                return ResourceManager.GetString("CmdSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen.
        /// </summary>
        public static string CmdSettings {
            get {
                return ResourceManager.GetString("CmdSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich.
        /// </summary>
        public static string CmdUser {
            get {
                return ResourceManager.GetString("CmdUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja.
        /// </summary>
        public static string CmdYes {
            get {
                return ResourceManager.GetString("CmdYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle.
        /// </summary>
        public static string EnumArchivedAll {
            get {
                return ResourceManager.GetString("EnumArchivedAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuelle.
        /// </summary>
        public static string EnumArchivedCurrent {
            get {
                return ResourceManager.GetString("EnumArchivedCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vergangene.
        /// </summary>
        public static string EnumArchivedOld {
            get {
                return ResourceManager.GetString("EnumArchivedOld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbunden.
        /// </summary>
        public static string EnumConnConnected {
            get {
                return ResourceManager.GetString("EnumConnConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindungsaufbau.
        /// </summary>
        public static string EnumConnConnecting {
            get {
                return ResourceManager.GetString("EnumConnConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließe Verbindung.
        /// </summary>
        public static string EnumConnDisconnecting {
            get {
                return ResourceManager.GetString("EnumConnDisconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offline.
        /// </summary>
        public static string EnumConnDisonnected {
            get {
                return ResourceManager.GetString("EnumConnDisonnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        public static string EnumDeviceTypeBrowser {
            get {
                return ResourceManager.GetString("EnumDeviceTypeBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Computer.
        /// </summary>
        public static string EnumDeviceTypePc {
            get {
                return ResourceManager.GetString("EnumDeviceTypePc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verfolgte Ideen.
        /// </summary>
        public static string EnumFilterFollowingIdeas {
            get {
                return ResourceManager.GetString("EnumFilterFollowingIdeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meine Ideen.
        /// </summary>
        public static string EnumFilterMyIdeas {
            get {
                return ResourceManager.GetString("EnumFilterMyIdeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keiner.
        /// </summary>
        public static string EnumFilterNone {
            get {
                return ResourceManager.GetString("EnumFilterNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Organisation.
        /// </summary>
        public static string EnumOrganizationNone {
            get {
                return ResourceManager.GetString("EnumOrganizationNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string EnumOrganizationNormal {
            get {
                return ResourceManager.GetString("EnumOrganizationNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Öffentlich.
        /// </summary>
        public static string EnumOrganizationPublic {
            get {
                return ResourceManager.GetString("EnumOrganizationPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten lesen.
        /// </summary>
        public static string EnumUserRightRead {
            get {
                return ResourceManager.GetString("EnumUserRightRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten bearbeiten.
        /// </summary>
        public static string EnumUserRightReadWrite {
            get {
                return ResourceManager.GetString("EnumUserRightReadWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string EnumUserRoleAdmin {
            get {
                return ResourceManager.GetString("EnumUserRoleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SysAdmin.
        /// </summary>
        public static string EnumUserRoleSysAdmin {
            get {
                return ResourceManager.GetString("EnumUserRoleSysAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer.
        /// </summary>
        public static string EnumUserRoleUser {
            get {
                return ResourceManager.GetString("EnumUserRoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Plus.
        /// </summary>
        public static string EnumUserRoleUserPlus {
            get {
                return ResourceManager.GetString("EnumUserRoleUserPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Daten.
        /// </summary>
        public static string LblLoading {
            get {
                return ResourceManager.GetString("LblLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zugriffstoken.
        /// </summary>
        public static string LbLToken {
            get {
                return ResourceManager.GetString("LbLToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REST Token für Zugriff.
        /// </summary>
        public static string LblTokenDetails {
            get {
                return ResourceManager.GetString("LblTokenDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unbekannt.
        /// </summary>
        public static string LblUnknown {
            get {
                return ResourceManager.GetString("LblUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speichern leider nicht möglich..
        /// </summary>
        public static string MsgCannotSave {
            get {
                return ResourceManager.GetString("MsgCannotSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier kannst du in Zukunft mit allen Unterstützern über die Idee chatten..
        /// </summary>
        public static string MsgDevChatIdea {
            get {
                return ResourceManager.GetString("MsgDevChatIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier kannst du in Zukunft direkt mit dem Ersteller der Idee chatten..
        /// </summary>
        public static string MsgDevChatUser {
            get {
                return ResourceManager.GetString("MsgDevChatUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Löschen des Token:.
        /// </summary>
        public static string MsgErrorDeleteToken {
            get {
                return ResourceManager.GetString("MsgErrorDeleteToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Sichern des Token:.
        /// </summary>
        public static string MsgErrorSaveToken {
            get {
                return ResourceManager.GetString("MsgErrorSaveToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header Infos!.
        /// </summary>
        public static string MsgHeaderInfos {
            get {
                return ResourceManager.GetString("MsgHeaderInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info! Dieser Command wird nicht selektiert!.
        /// </summary>
        public static string MsgInfo {
            get {
                return ResourceManager.GetString("MsgInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Account wurde gesperrt. Sie werden jetzt abgemeldet..
        /// </summary>
        public static string MsgLocked {
            get {
                return ResourceManager.GetString("MsgLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht möglich, da keine Verbindung zum Server besteht..
        /// </summary>
        public static string MsgNotConnected {
            get {
                return ResourceManager.GetString("MsgNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nicht gespeicherte Daten gehen verloren.
        ///Möchtest du fortfahren?.
        /// </summary>
        public static string MsgNotSaved {
            get {
                return ResourceManager.GetString("MsgNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Für die Nutzung von LENIE musst du zuerst deine Telefonnummer bestätigen!.
        /// </summary>
        public static string MsgPhoneConfirmation {
            get {
                return ResourceManager.GetString("MsgPhoneConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonnummer bestätigen!.
        /// </summary>
        public static string MsgPhoneConfirmationTitle {
            get {
                return ResourceManager.GetString("MsgPhoneConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string MsgTitleEmail {
            get {
                return ResourceManager.GetString("MsgTitleEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        public static string MsgTitleError {
            get {
                return ResourceManager.GetString("MsgTitleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string MsgTitleHeaderInfos {
            get {
                return ResourceManager.GetString("MsgTitleHeaderInfos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string MsgTitleInfo {
            get {
                return ResourceManager.GetString("MsgTitleInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account-Sperre.
        /// </summary>
        public static string MsgTitleLocked {
            get {
                return ResourceManager.GetString("MsgTitleLocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbindung.
        /// </summary>
        public static string MsgTitleNotConnected {
            get {
                return ResourceManager.GetString("MsgTitleNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achtung.
        /// </summary>
        public static string MsgTitleNotSaved {
            get {
                return ResourceManager.GetString("MsgTitleNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serverfehler.
        /// </summary>
        public static string MsgTitleServerError {
            get {
                return ResourceManager.GetString("MsgTitleServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Version.
        /// </summary>
        public static string MsgTitleUpdateAvailable {
            get {
                return ResourceManager.GetString("MsgTitleUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Version.
        /// </summary>
        public static string MsgTitleUpdateMandatory {
            get {
                return ResourceManager.GetString("MsgTitleUpdateMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eingabefehler.
        /// </summary>
        public static string MsgTitleValidationError {
            get {
                return ResourceManager.GetString("MsgTitleValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token wurde in die Zwischenablage kopiert..
        /// </summary>
        public static string MsgTokenInClipboard {
            get {
                return ResourceManager.GetString("MsgTokenInClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine aktualisiert Version ({0}) der App ist vorhanden..
        /// </summary>
        public static string MsgUpdateAvailable {
            get {
                return ResourceManager.GetString("MsgUpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine aktualisiert Version ({0}) der App ist vorhanden. Bitte aktualisieren Sie die App. App wird jetzt beendet!.
        /// </summary>
        public static string MsgUpdateMandatory {
            get {
                return ResourceManager.GetString("MsgUpdateMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine gültige E-Mail.
        /// </summary>
        public static string ValNoEmail {
            get {
                return ResourceManager.GetString("ValNoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine gültige Telefonnummer: +43660123456.
        /// </summary>
        public static string ValNoPhone {
            get {
                return ResourceManager.GetString("ValNoPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pflichtfeld.
        /// </summary>
        public static string ValNotEmpty {
            get {
                return ResourceManager.GetString("ValNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leerzeichen nicht erlaubt.
        /// </summary>
        public static string ValNoWhitespace {
            get {
                return ResourceManager.GetString("ValNoWhitespace", resourceCulture);
            }
        }
    }
}
