//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResSysAdmin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResSysAdmin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResSysAdmin", typeof(ResSysAdmin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Daten ....
        /// </summary>
        public static string BusyLoading {
            get {
                return ResourceManager.GetString("BusyLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualisieren.
        /// </summary>
        public static string CmdCommonInfo {
            get {
                return ResourceManager.GetString("CmdCommonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leider ist ein Fehler aufgetreten.
        /// </summary>
        public static string ErrorCommon {
            get {
                return ResourceManager.GetString("ErrorCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wartungsnachricht.
        /// </summary>
        public static string LbLCommonMsg {
            get {
                return ResourceManager.GetString("LbLCommonMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Nachricht wird jedem Benutzer angezeigt.
        /// </summary>
        public static string LbLCommonMsgDetails {
            get {
                return ResourceManager.GetString("LbLCommonMsgDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Systembenutzer.
        /// </summary>
        public static string LblUsers {
            get {
                return ResourceManager.GetString("LblUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Benutzer des Systems.
        /// </summary>
        public static string LbLUsersDetails {
            get {
                return ResourceManager.GetString("LbLUsersDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachricht.
        /// </summary>
        public static string MsgCommonInfo {
            get {
                return ResourceManager.GetString("MsgCommonInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allgemeine Nachricht an alle User.
        /// </summary>
        public static string MsgCommonInfoPlaceholder {
            get {
                return ResourceManager.GetString("MsgCommonInfoPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration des Systems.
        /// </summary>
        public static string SubTitel {
            get {
                return ResourceManager.GetString("SubTitel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Titel {
            get {
                return ResourceManager.GetString("Titel", resourceCulture);
            }
        }
    }
}
