//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewLogin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewLogin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewLogin", typeof(ResViewLogin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bei der Arbeit ....
        /// </summary>
        public static string BsyLogin {
            get {
                return ResourceManager.GetString("BsyLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiter.
        /// </summary>
        public static string CmdContinue {
            get {
                return ResourceManager.GetString("CmdContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort vergessen.
        /// </summary>
        public static string CmdForgotPassword {
            get {
                return ResourceManager.GetString("CmdForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string CmdLogin {
            get {
                return ResourceManager.GetString("CmdLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrieren.
        /// </summary>
        public static string CmdRegister {
            get {
                return ResourceManager.GetString("CmdRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestätigungs Mail erneut senden.
        /// </summary>
        public static string CmdResendAccessLink {
            get {
                return ResourceManager.GetString("CmdResendAccessLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestehender oder neuer Login.
        /// </summary>
        public static string EntryPlaceholderLoginName {
            get {
                return ResourceManager.GetString("EntryPlaceholderLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort eingeben.
        /// </summary>
        public static string EntryPlaceholderPassword {
            get {
                return ResourceManager.GetString("EntryPlaceholderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string EntryTitleLoginName {
            get {
                return ResourceManager.GetString("EntryTitleLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        public static string EntryTitlePassword {
            get {
                return ResourceManager.GetString("EntryTitlePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Ste [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LblInfoText {
            get {
                return ResourceManager.GetString("LblInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string LblInfoTitle {
            get {
                return ResourceManager.GetString("LblInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmelden.
        /// </summary>
        public static string LblLogin {
            get {
                return ResourceManager.GetString("LblLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login für Benutzer.
        /// </summary>
        public static string LblMainData {
            get {
                return ResourceManager.GetString("LblMainData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neu hier?.
        /// </summary>
        public static string LblRegister {
            get {
                return ResourceManager.GetString("LblRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angemeldet bleiben.
        /// </summary>
        public static string LblStayLoggedIn {
            get {
                return ResourceManager.GetString("LblStayLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anmelden oder neu registrieren.
        /// </summary>
        public static string LblSubTitle {
            get {
                return ResourceManager.GetString("LblSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string LblTitle {
            get {
                return ResourceManager.GetString("LblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wende dich an die verantworliche Person in deiner Gemeinde, um ein Konto anzulegen..
        /// </summary>
        public static string MsgCannotCreateAccount {
            get {
                return ResourceManager.GetString("MsgCannotCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestätigungs Mail wurde versandt..
        /// </summary>
        public static string MsgConfirmationSent {
            get {
                return ResourceManager.GetString("MsgConfirmationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte gib zuerst deine EMail Addresse ein..
        /// </summary>
        public static string MsgEnterMail {
            get {
                return ResourceManager.GetString("MsgEnterMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es existiert bereits ein Account mit dieser EMail. Möchtest du dich direkt anmelden?.
        /// </summary>
        public static string MsgExistingUser {
            get {
                return ResourceManager.GetString("MsgExistingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kein Account mit dieser EMail. Wollen Sie einen neuen Account erstellen?.
        /// </summary>
        public static string MsgNewUser {
            get {
                return ResourceManager.GetString("MsgNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine Mail zum Zurücksetzen des Passworts wurde gesendet..
        /// </summary>
        public static string MsgResetSent {
            get {
                return ResourceManager.GetString("MsgResetSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler beim Versenden der Mail ist aufgetreten..
        /// </summary>
        public static string MsgSendError {
            get {
                return ResourceManager.GetString("MsgSendError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string MsgTitleExistingUser {
            get {
                return ResourceManager.GetString("MsgTitleExistingUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string MsgTitleNewUser {
            get {
                return ResourceManager.GetString("MsgTitleNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort.
        /// </summary>
        public static string MsgTitleWrongPassword {
            get {
                return ResourceManager.GetString("MsgTitleWrongPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Login-Name wurde nicht bestätigt. Bitte prüfen Sie Ihren Posteingang..
        /// </summary>
        public static string MsgUserNotValidated {
            get {
                return ResourceManager.GetString("MsgUserNotValidated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungültiges Passwort.
        /// </summary>
        public static string MsgWrongPassword {
            get {
                return ResourceManager.GetString("MsgWrongPassword", resourceCulture);
            }
        }
    }
}
