//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewChatOverview {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewChatOverview() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewChatOverview", typeof(ResViewChatOverview).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchen.
        /// </summary>
        public static string CmdSearch {
            get {
                return ResourceManager.GetString("CmdSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachricht.
        /// </summary>
        public static string EntryChatPlaceholder {
            get {
                return ResourceManager.GetString("EntryChatPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachricht.
        /// </summary>
        public static string EntryChatTitle {
            get {
                return ResourceManager.GetString("EntryChatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche nach Titel, Beschreibung, User.
        /// </summary>
        public static string EntrySearchTextPlaceholder {
            get {
                return ResourceManager.GetString("EntrySearchTextPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche.
        /// </summary>
        public static string EntrySearchTextTitle {
            get {
                return ResourceManager.GetString("EntrySearchTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle verfügbaren Chats.
        /// </summary>
        public static string LblChatInfoAll {
            get {
                return ResourceManager.GetString("LblChatInfoAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chats zur Idee.
        /// </summary>
        public static string LblChatInfoIdea {
            get {
                return ResourceManager.GetString("LblChatInfoIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chats der Gemeinde: {0}.
        /// </summary>
        public static string LblChatInfoTown {
            get {
                return ResourceManager.GetString("LblChatInfoTown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chats.
        /// </summary>
        public static string LblChats {
            get {
                return ResourceManager.GetString("LblChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat zu.
        /// </summary>
        public static string LblChatWith {
            get {
                return ResourceManager.GetString("LblChatWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ideen.
        /// </summary>
        public static string LblIdeas {
            get {
                return ResourceManager.GetString("LblIdeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Chats.
        /// </summary>
        public static string LblLoadingChats {
            get {
                return ResourceManager.GetString("LblLoadingChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Ideen.
        /// </summary>
        public static string LblLoadingIdeas {
            get {
                return ResourceManager.GetString("LblLoadingIdeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Gemeinden.
        /// </summary>
        public static string LblLoadingTowns {
            get {
                return ResourceManager.GetString("LblLoadingTowns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leider gibt es dazu noch keine Chats.
        /// </summary>
        public static string LblNoChats {
            get {
                return ResourceManager.GetString("LblNoChats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Ideen.
        /// </summary>
        public static string LblPickerAllIdeas {
            get {
                return ResourceManager.GetString("LblPickerAllIdeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle Gemeinden.
        /// </summary>
        public static string LblPickerAllTowns {
            get {
                return ResourceManager.GetString("LblPickerAllTowns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mit Erstellern und Unterstützern über die Idee chatten.
        /// </summary>
        public static string LblSubTitle {
            get {
                return ResourceManager.GetString("LblSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meine Chats.
        /// </summary>
        public static string LblTitle {
            get {
                return ResourceManager.GetString("LblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemeinden.
        /// </summary>
        public static string LblTowns {
            get {
                return ResourceManager.GetString("LblTowns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivität nicht verfügbar.
        /// </summary>
        public static string MsgCouldNotNavToIdea {
            get {
                return ResourceManager.GetString("MsgCouldNotNavToIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es tut uns leid, wir konnten den Chat nicht öffnen!.
        /// </summary>
        public static string MsgCouldNotOpenChat {
            get {
                return ResourceManager.GetString("MsgCouldNotOpenChat", resourceCulture);
            }
        }
    }
}
