//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewShowReports {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewShowReports() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewShowReports", typeof(ResViewShowReports).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Idee Löschen.
        /// </summary>
        public static string BtnDeleteIdea {
            get {
                return ResourceManager.GetString("BtnDeleteIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivität löschen.
        /// </summary>
        public static string CmdDeleteIdea {
            get {
                return ResourceManager.GetString("CmdDeleteIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meldung löschen.
        /// </summary>
        public static string CmdDeleteReport {
            get {
                return ResourceManager.GetString("CmdDeleteReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Idee wurde noch nicht gemeldet..
        /// </summary>
        public static string LblNoReports {
            get {
                return ResourceManager.GetString("LblNoReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meldungen.
        /// </summary>
        public static string LblTitle {
            get {
                return ResourceManager.GetString("LblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string ListHeaderDelete {
            get {
                return ResourceManager.GetString("ListHeaderDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string ListHeaderName {
            get {
                return ResourceManager.GetString("ListHeaderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grund.
        /// </summary>
        public static string ListHeaderReason {
            get {
                return ResourceManager.GetString("ListHeaderReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchtest du deine Idee wirklich löschen? .
        /// </summary>
        public static string MsgDeleteIdeaConfirm {
            get {
                return ResourceManager.GetString("MsgDeleteIdeaConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchtest du die Meldung wirklich löschen? .
        /// </summary>
        public static string MsgDeleteReportConfirm {
            get {
                return ResourceManager.GetString("MsgDeleteReportConfirm", resourceCulture);
            }
        }
    }
}
