//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewAddIdea {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewAddIdea() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewAddIdea", typeof(ResViewAddIdea).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beteiligen.
        /// </summary>
        public static string CmdAddHelper {
            get {
                return ResourceManager.GetString("CmdAddHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hinzufügen.
        /// </summary>
        public static string CmdAddNeed {
            get {
                return ResourceManager.GetString("CmdAddNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hinzufügen.
        /// </summary>
        public static string CmdAddRegion {
            get {
                return ResourceManager.GetString("CmdAddRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In meinem Kalender eintragen.
        /// </summary>
        public static string CmdAddToCalendar {
            get {
                return ResourceManager.GetString("CmdAddToCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string CmdChatHelper {
            get {
                return ResourceManager.GetString("CmdChatHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entfernen.
        /// </summary>
        public static string CmdDeleteHelper {
            get {
                return ResourceManager.GetString("CmdDeleteHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivität löschen.
        /// </summary>
        public static string CmdDeleteIdea {
            get {
                return ResourceManager.GetString("CmdDeleteIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entfernen.
        /// </summary>
        public static string CmdDeleteImage {
            get {
                return ResourceManager.GetString("CmdDeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entfernen.
        /// </summary>
        public static string CmdDeleteNeed {
            get {
                return ResourceManager.GetString("CmdDeleteNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beteiligen.
        /// </summary>
        public static string CmdEditHelper {
            get {
                return ResourceManager.GetString("CmdEditHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        public static string CmdEditImage {
            get {
                return ResourceManager.GetString("CmdEditImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to editieren.
        /// </summary>
        public static string CmdEditNeed {
            get {
                return ResourceManager.GetString("CmdEditNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position ändern.
        /// </summary>
        public static string CmdEditPosition {
            get {
                return ResourceManager.GetString("CmdEditPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position nicht ändern.
        /// </summary>
        public static string CmdEndEditPosition {
            get {
                return ResourceManager.GetString("CmdEndEditPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privater Chat mit dem Ideengeber.
        /// </summary>
        public static string CmdPrivateChat {
            get {
                return ResourceManager.GetString("CmdPrivateChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gruppenchat.
        /// </summary>
        public static string CmdPublicChat {
            get {
                return ResourceManager.GetString("CmdPublicChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemeinde entfernen.
        /// </summary>
        public static string CmdRemoveRegion {
            get {
                return ResourceManager.GetString("CmdRemoveRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivität als unangebracht melden.
        /// </summary>
        public static string CmdReportIdea {
            get {
                return ResourceManager.GetString("CmdReportIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gib eine Addresse als Ort der Idee an.
        /// </summary>
        public static string EntryAddressPlaceholder {
            get {
                return ResourceManager.GetString("EntryAddressPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string EntryAddressTitle {
            get {
                return ResourceManager.GetString("EntryAddressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurzbeschreibung der Idee.
        /// </summary>
        public static string EntryPlaceholderDescription {
            get {
                return ResourceManager.GetString("EntryPlaceholderDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meine Idee.
        /// </summary>
        public static string EntryPlaceholderTitle {
            get {
                return ResourceManager.GetString("EntryPlaceholderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kurzbeschreibung.
        /// </summary>
        public static string EntryTitleDescription {
            get {
                return ResourceManager.GetString("EntryTitleDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meine Idee.
        /// </summary>
        public static string EntryTitleTitle {
            get {
                return ResourceManager.GetString("EntryTitleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktionen.
        /// </summary>
        public static string LblActions {
            get {
                return ResourceManager.GetString("LblActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beschreibung.
        /// </summary>
        public static string LblDescription {
            get {
                return ResourceManager.GetString("LblDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personen, die bei der Umsetzung mithelfen.
        /// </summary>
        public static string LblHelperSubTitle {
            get {
                return ResourceManager.GetString("LblHelperSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterstützungen.
        /// </summary>
        public static string LblHelperTitle {
            get {
                return ResourceManager.GetString("LblHelperTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild.
        /// </summary>
        public static string LblImage {
            get {
                return ResourceManager.GetString("LblImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild und Details.
        /// </summary>
        public static string LblImageAndDetails {
            get {
                return ResourceManager.GetString("LblImageAndDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier kannst du ein aussagekräftiges Bild deiner Idee hochladen.
        /// </summary>
        public static string LblImageInfo {
            get {
                return ResourceManager.GetString("LblImageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Idee ...
        /// </summary>
        public static string LblLoadIdea {
            get {
                return ResourceManager.GetString("LblLoadIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benötigte Ressourcen.
        /// </summary>
        public static string LblNeeds {
            get {
                return ResourceManager.GetString("LblNeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to z.B. Equipment, Wissen, Personenanzahl… .
        /// </summary>
        public static string LblNeedSubTitle {
            get {
                return ResourceManager.GetString("LblNeedSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ich brauche.
        /// </summary>
        public static string LblNeedTitle {
            get {
                return ResourceManager.GetString("LblNeedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterstütze die Idee!.
        /// </summary>
        public static string LblNoHelpers {
            get {
                return ResourceManager.GetString("LblNoHelpers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivität hat keine benötigten Ressourcen. .
        /// </summary>
        public static string LblNoNeeds {
            get {
                return ResourceManager.GetString("LblNoNeeds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Gemeinde mehr hinterlegt.
        /// </summary>
        public static string LblNoOtherTowns {
            get {
                return ResourceManager.GetString("LblNoOtherTowns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dieser Helfer hat keine Ressourcen angegeben..
        /// </summary>
        public static string LblNoSupports {
            get {
                return ResourceManager.GetString("LblNoSupports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standort.
        /// </summary>
        public static string LblPosition {
            get {
                return ResourceManager.GetString("LblPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standort angeben.
        /// </summary>
        public static string LblPositionEdit {
            get {
                return ResourceManager.GetString("LblPositionEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst den Ort der Idee entweder in der Karte setzen oder nach einer Adresse suchen..
        /// </summary>
        public static string LblPositionInfo {
            get {
                return ResourceManager.GetString("LblPositionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pin in der Karte setzen.
        /// </summary>
        public static string LblPositionPinMode {
            get {
                return ResourceManager.GetString("LblPositionPinMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ort der Aktivität.
        /// </summary>
        public static string LblRegionListHeader {
            get {
                return ResourceManager.GetString("LblRegionListHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ort hinzufügen.
        /// </summary>
        public static string LblRegionListHeaderNew {
            get {
                return ResourceManager.GetString("LblRegionListHeaderNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string LblSubTitle {
            get {
                return ResourceManager.GetString("LblSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  .
        /// </summary>
        public static string LblSupportsSubTitle {
            get {
                return ResourceManager.GetString("LblSupportsSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ressourcen.
        /// </summary>
        public static string LblSupportsTitle {
            get {
                return ResourceManager.GetString("LblSupportsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to von.
        /// </summary>
        public static string LblTimeFrom {
            get {
                return ResourceManager.GetString("LblTimeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeitraum.
        /// </summary>
        public static string LblTimeSpan {
            get {
                return ResourceManager.GetString("LblTimeSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeitraum angeben.
        /// </summary>
        public static string LblTimeSpanEdit {
            get {
                return ResourceManager.GetString("LblTimeSpanEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to bis.
        /// </summary>
        public static string LblTimeTo {
            get {
                return ResourceManager.GetString("LblTimeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idee.
        /// </summary>
        public static string LblTitle {
            get {
                return ResourceManager.GetString("LblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchtest du den Helfer wirklich entfernen? .
        /// </summary>
        public static string MsgConfirmHelperDelete {
            get {
                return ResourceManager.GetString("MsgConfirmHelperDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchtest du die Idee wirklich entfernen? .
        /// </summary>
        public static string MsgConfirmIdeaDelete {
            get {
                return ResourceManager.GetString("MsgConfirmIdeaDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchtest du die Ressource wirklich entfernen? .
        /// </summary>
        public static string MsgConfirmNeedDelete {
            get {
                return ResourceManager.GetString("MsgConfirmNeedDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchtest du die Gemeinde von deiner Idee wirklich ausschließen? .
        /// </summary>
        public static string MsgConfirmRegionDelete {
            get {
                return ResourceManager.GetString("MsgConfirmRegionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konnte nicht gelöscht werden..
        /// </summary>
        public static string MsgDeleteFail {
            get {
                return ResourceManager.GetString("MsgDeleteFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte zuerst die Änderungen der benötigten Ressource sichern..
        /// </summary>
        public static string MsgNeedsSave {
            get {
                return ResourceManager.GetString("MsgNeedsSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnte leider keine Addresse für die ausgewählte Position gefunden werden..
        /// </summary>
        public static string MsgNoAddressFound {
            get {
                return ResourceManager.GetString("MsgNoAddressFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte gib eine Addresse zum Suchen ein.
        /// </summary>
        public static string MsgNoAddressToSearch {
            get {
                return ResourceManager.GetString("MsgNoAddressToSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es konnte leider keine Position mit der gegebenen Addresse gefunden werden..
        /// </summary>
        public static string MsgNoPositionFound {
            get {
                return ResourceManager.GetString("MsgNoPositionFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte gib einen Ort für deine Idee an..
        /// </summary>
        public static string ValErrorAddress {
            get {
                return ResourceManager.GetString("ValErrorAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte wähle eine deiner Gemeinden für die Idee aus..
        /// </summary>
        public static string ValErrorNoCompanies {
            get {
                return ResourceManager.GetString("ValErrorNoCompanies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte setze zuerst eine Position auf der Karte..
        /// </summary>
        public static string ValErrorPosition {
            get {
                return ResourceManager.GetString("ValErrorPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ende muss nach Anfang liegen..
        /// </summary>
        public static string ValErrorTimeFrame {
            get {
                return ResourceManager.GetString("ValErrorTimeFrame", resourceCulture);
            }
        }
    }
}
