//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewAddOrganizationUser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewAddOrganizationUser() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewAddOrganizationUser", typeof(ResViewAddOrganizationUser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail des User.
        /// </summary>
        public static string EntryPlaceholderEmail {
            get {
                return ResourceManager.GetString("EntryPlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail.
        /// </summary>
        public static string EntryTitleEmail {
            get {
                return ResourceManager.GetString("EntryTitleEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falls der User bereits im System (andere Firma) bekannt ist wird dieser verwendet. Ein neuer User bekommt eine E-Mail mit seinen Zugangsdaten. Admins können alle Firmeneinstellungen und die gesamte Infrastuktur bearbeiten. User mit Bearbeitungsrecht können die gesamte Infrastruktur bearbeiten. User mit Leserecht können die Infrastuktur nur ansehen..
        /// </summary>
        public static string LblInfoText {
            get {
                return ResourceManager.GetString("LblInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string LblInfoTitle {
            get {
                return ResourceManager.GetString("LblInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stammdaten.
        /// </summary>
        public static string LblMainData {
            get {
                return ResourceManager.GetString("LblMainData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User einer Organisation.
        /// </summary>
        public static string LblSubTitle {
            get {
                return ResourceManager.GetString("LblSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string LblTitle {
            get {
                return ResourceManager.GetString("LblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechte des Benutzers:.
        /// </summary>
        public static string LblUserRights {
            get {
                return ResourceManager.GetString("LblUserRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolle des Benutzers:.
        /// </summary>
        public static string LblUserRoles {
            get {
                return ResourceManager.GetString("LblUserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer bereits in System..
        /// </summary>
        public static string ValUserDuplicate {
            get {
                return ResourceManager.GetString("ValUserDuplicate", resourceCulture);
            }
        }
    }
}
