//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewSettingsPush {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewSettingsPush() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewSettingsPush", typeof(ResViewSettingsPush).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle aus.
        /// </summary>
        public static string CmdAllOff {
            get {
                return ResourceManager.GetString("CmdAllOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle an.
        /// </summary>
        public static string CmdAllOn {
            get {
                return ResourceManager.GetString("CmdAllOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Settings.
        /// </summary>
        public static string CmdOpenSettings {
            get {
                return ResourceManager.GetString("CmdOpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TestPush senden.
        /// </summary>
        public static string CmdSendPush {
            get {
                return ResourceManager.GetString("CmdSendPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Stet clita kasd gubergren, no sea takimata sanctus est Lorem ipsum dolor sit amet. Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero eos et accusam et justo duo dolores et ea rebum. Ste [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LblInfoText {
            get {
                return ResourceManager.GetString("LblInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string LblInfoTitle {
            get {
                return ResourceManager.GetString("LblInfoTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chatnachrichten.
        /// </summary>
        public static string LblMailChat {
            get {
                return ResourceManager.GetString("LblMailChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erinnerungen Termine.
        /// </summary>
        public static string LblMailMeeting {
            get {
                return ResourceManager.GetString("LblMailMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Mail Benachrichtigungen.
        /// </summary>
        public static string LblMailNotifications {
            get {
                return ResourceManager.GetString("LblMailNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meldung.
        /// </summary>
        public static string LblMailReport {
            get {
                return ResourceManager.GetString("LblMailReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push aktiv:.
        /// </summary>
        public static string LblPushActive {
            get {
                return ResourceManager.GetString("LblPushActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chatnachrichten.
        /// </summary>
        public static string LblPushChat {
            get {
                return ResourceManager.GetString("LblPushChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommentar.
        /// </summary>
        public static string LblPushComment {
            get {
                return ResourceManager.GetString("LblPushComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to neue Ideen.
        /// </summary>
        public static string LblPushIdea {
            get {
                return ResourceManager.GetString("LblPushIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pushes deaktiviert.
        /// </summary>
        public static string LblPushInactive {
            get {
                return ResourceManager.GetString("LblPushInactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like.
        /// </summary>
        public static string LblPushLike {
            get {
                return ResourceManager.GetString("LblPushLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erinnerungen Termine.
        /// </summary>
        public static string LblPushMeeting {
            get {
                return ResourceManager.GetString("LblPushMeeting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meldung.
        /// </summary>
        public static string LblPushReport {
            get {
                return ResourceManager.GetString("LblPushReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterstützung.
        /// </summary>
        public static string LblPushSupport {
            get {
                return ResourceManager.GetString("LblPushSupport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push Benachrichtigungen:.
        /// </summary>
        public static string LblPushTasks {
            get {
                return ResourceManager.GetString("LblPushTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einstellungen für Benachrichtigungen.
        /// </summary>
        public static string LblSubTitle {
            get {
                return ResourceManager.GetString("LblSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle 10 Minuten Push Benachrichtigung .
        /// </summary>
        public static string LblTenMinPush {
            get {
                return ResourceManager.GetString("LblTenMinPush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benachrichtigungen.
        /// </summary>
        public static string LblTitle {
            get {
                return ResourceManager.GetString("LblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topics:.
        /// </summary>
        public static string LblTopics {
            get {
                return ResourceManager.GetString("LblTopics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Einstellung konnte nicht übernommen werden..
        /// </summary>
        public static string MsgSettingsNotSaved {
            get {
                return ResourceManager.GetString("MsgSettingsNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        public static string MsgTitleSettingsNotSaved {
            get {
                return ResourceManager.GetString("MsgTitleSettingsNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler.
        /// </summary>
        public static string MsgTitleTopicNotSaved {
            get {
                return ResourceManager.GetString("MsgTitleTopicNotSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Topic konnte nicht im DC gespeichert werden..
        /// </summary>
        public static string MsgTopicNotSaved {
            get {
                return ResourceManager.GetString("MsgTopicNotSaved", resourceCulture);
            }
        }
    }
}
