//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewMainIdea {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewMainIdea() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewMainIdea", typeof(ResViewMainIdea).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Idee.
        /// </summary>
        public static string CmdAddIdea {
            get {
                return ResourceManager.GetString("CmdAddIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter zurücksetzen.
        /// </summary>
        public static string CmdFilterClear {
            get {
                return ResourceManager.GetString("CmdFilterClear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suchen.
        /// </summary>
        public static string CmdSearch {
            get {
                return ResourceManager.GetString("CmdSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starte deine neue Idee.
        /// </summary>
        public static string EntryNewPlaceholder {
            get {
                return ResourceManager.GetString("EntryNewPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Idee.
        /// </summary>
        public static string EntryNewTitle {
            get {
                return ResourceManager.GetString("EntryNewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel, User, etc..
        /// </summary>
        public static string EntrySearchTextPlaceholder {
            get {
                return ResourceManager.GetString("EntrySearchTextPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche.
        /// </summary>
        public static string EntrySearchTextTitle {
            get {
                return ResourceManager.GetString("EntrySearchTextTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Archiv:.
        /// </summary>
        public static string LblArchivedFilter {
            get {
                return ResourceManager.GetString("LblArchivedFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Idee erstellen:.
        /// </summary>
        public static string LblCreateIdea {
            get {
                return ResourceManager.GetString("LblCreateIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter:.
        /// </summary>
        public static string LblFilter {
            get {
                return ResourceManager.GetString("LblFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle meine Gemeinden.
        /// </summary>
        public static string LblFilterAllTowns {
            get {
                return ResourceManager.GetString("LblFilterAllTowns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivität auf Karte.
        /// </summary>
        public static string LblIdeaMapTitle {
            get {
                return ResourceManager.GetString("LblIdeaMapTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivität kann nicht angezeigt werden.
        /// </summary>
        public static string LblIdeaNotAvailable {
            get {
                return ResourceManager.GetString("LblIdeaNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machen &amp; Helfen.
        /// </summary>
        public static string LblIdeaWorkshop {
            get {
                return ResourceManager.GetString("LblIdeaWorkshop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktivitäten werden geladen ....
        /// </summary>
        public static string LblLoadingIdeas {
            get {
                return ResourceManager.GetString("LblLoadingIdeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es wurden noch keine Ideen geladen oder es existieren noch keine in deiner Gemeinde. Bitte .
        /// </summary>
        public static string LblNoIdeasText1 {
            get {
                return ResourceManager.GetString("LblNoIdeasText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ziehe.
        /// </summary>
        public static string LblNoIdeasText2 {
            get {
                return ResourceManager.GetString("LblNoIdeasText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  diesen Bereich nach unten um Ideen zu laden..
        /// </summary>
        public static string LblNoIdeasText3 {
            get {
                return ResourceManager.GetString("LblNoIdeasText3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst alternativ auch auf das Symbol drücken um die Daten neu zu laden..
        /// </summary>
        public static string LblNoIdeasText4 {
            get {
                return ResourceManager.GetString("LblNoIdeasText4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starte hier deine Ideen und sammle fleissige Unterstützer.
        /// </summary>
        public static string LblSubTitle {
            get {
                return ResourceManager.GetString("LblSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorhandene Ideen unterstützen:.
        /// </summary>
        public static string LblSupportIdea {
            get {
                return ResourceManager.GetString("LblSupportIdea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machen &amp; Helfen.
        /// </summary>
        public static string LblTitle {
            get {
                return ResourceManager.GetString("LblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemeinde:.
        /// </summary>
        public static string LblTownFilter {
            get {
                return ResourceManager.GetString("LblTownFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchtest du deine Idee wirklich löschen? .
        /// </summary>
        public static string MsgDeleteConfirm {
            get {
                return ResourceManager.GetString("MsgDeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Idee konnte nicht gelöscht werden..
        /// </summary>
        public static string MsgDeleteError {
            get {
                return ResourceManager.GetString("MsgDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Möchtest du deine Unterstützung wirklich zurückziehen?.
        /// </summary>
        public static string MsgDeleteHelperConfirm {
            get {
                return ResourceManager.GetString("MsgDeleteHelperConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Idee konnte nicht geliked werden..
        /// </summary>
        public static string MsgLikeError {
            get {
                return ResourceManager.GetString("MsgLikeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um eine Idee anzulegen, musst du zuerst eine Hauptgemeinde festlegen..
        /// </summary>
        public static string MsgNeedHometown {
            get {
                return ResourceManager.GetString("MsgNeedHometown", resourceCulture);
            }
        }
    }
}
