//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewIdeaDetails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewIdeaDetails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewIdeaDetails", typeof(ResViewIdeaDetails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beteiligen.
        /// </summary>
        public static string CmdAddHelper {
            get {
                return ResourceManager.GetString("CmdAddHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helfer entfernen.
        /// </summary>
        public static string CmdDeleteHelper {
            get {
                return ResourceManager.GetString("CmdDeleteHelper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idee löschen.
        /// </summary>
        public static string CmdDeleteItem {
            get {
                return ResourceManager.GetString("CmdDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idee bearbeiten.
        /// </summary>
        public static string CmdEditItem {
            get {
                return ResourceManager.GetString("CmdEditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karte vergrößern.
        /// </summary>
        public static string CmdShowMap {
            get {
                return ResourceManager.GetString("CmdShowMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du kannst diese Idee liken.
        /// </summary>
        public static string LblIsLikedFalse {
            get {
                return ResourceManager.GetString("LblIsLikedFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du magst diese Idee.
        /// </summary>
        public static string LblIsLikedTrue {
            get {
                return ResourceManager.GetString("LblIsLikedTrue", resourceCulture);
            }
        }
    }
}
