//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewEditUser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewEditUser() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewEditUser", typeof(ResViewEditUser).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prüfe Account ....
        /// </summary>
        public static string BsyCheckAccount {
            get {
                return ResourceManager.GetString("BsyCheckAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild entfernen.
        /// </summary>
        public static string CmdDeleteImage {
            get {
                return ResourceManager.GetString("CmdDeleteImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild ändern.
        /// </summary>
        public static string CmdEditImage {
            get {
                return ResourceManager.GetString("CmdEditImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meine Gemeinden verwalten.
        /// </summary>
        public static string CmdEditRegion {
            get {
                return ResourceManager.GetString("CmdEditRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weiter.
        /// </summary>
        public static string CmdLoginUser {
            get {
                return ResourceManager.GetString("CmdLoginUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon:.
        /// </summary>
        public static string EntryPhoneTitle {
            get {
                return ResourceManager.GetString("EntryPhoneTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EntryPlaceholderEmail {
            get {
                return ResourceManager.GetString("EntryPlaceholderEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname.
        /// </summary>
        public static string EntryPlaceholderFirstName {
            get {
                return ResourceManager.GetString("EntryPlaceholderFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname.
        /// </summary>
        public static string EntryPlaceholderLastName {
            get {
                return ResourceManager.GetString("EntryPlaceholderLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte neues Passwort eingeben.
        /// </summary>
        public static string EntryPlaceholderNewPassword {
            get {
                return ResourceManager.GetString("EntryPlaceholderNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonnummer.
        /// </summary>
        public static string EntryPlaceholderPhone {
            get {
                return ResourceManager.GetString("EntryPlaceholderPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suche PLZ oder Gemeinde.
        /// </summary>
        public static string EntryPlaceholderTownSearch {
            get {
                return ResourceManager.GetString("EntryPlaceholderTownSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string EntryTitleEmail {
            get {
                return ResourceManager.GetString("EntryTitleEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname:.
        /// </summary>
        public static string EntryTitleFirstName {
            get {
                return ResourceManager.GetString("EntryTitleFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname:.
        /// </summary>
        public static string EntryTitleLastName {
            get {
                return ResourceManager.GetString("EntryTitleLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neues Passwort:.
        /// </summary>
        public static string EntryTitleNewPassword {
            get {
                return ResourceManager.GetString("EntryTitleNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLZ oder Gemeinde:.
        /// </summary>
        public static string EntryTitleTownSearch {
            get {
                return ResourceManager.GetString("EntryTitleTownSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hauptgemeinde.
        /// </summary>
        public static string LblDefaultCompany {
            get {
                return ResourceManager.GetString("LblDefaultCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meine Gemeinden:.
        /// </summary>
        public static string LblEditRegion {
            get {
                return ResourceManager.GetString("LblEditRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login:.
        /// </summary>
        public static string LblLoginName {
            get {
                return ResourceManager.GetString("LblLoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stammdaten.
        /// </summary>
        public static string LblMainData {
            get {
                return ResourceManager.GetString("LblMainData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Gemeinden mit der Suche gefunden!.
        /// </summary>
        public static string LblNoTownsSearch {
            get {
                return ResourceManager.GetString("LblNoTownsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Gemeinden vorhanden!.
        /// </summary>
        public static string LblNoTownsSelected {
            get {
                return ResourceManager.GetString("LblNoTownsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optional.
        /// </summary>
        public static string LblOptional {
            get {
                return ResourceManager.GetString("LblOptional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwörter anzeigen.
        /// </summary>
        public static string LblShowPassword {
            get {
                return ResourceManager.GetString("LblShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigene Daten editieren.
        /// </summary>
        public static string LblSubTitle {
            get {
                return ResourceManager.GetString("LblSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benutzer.
        /// </summary>
        public static string LblTitle {
            get {
                return ResourceManager.GetString("LblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorname nicht gesetzt!.
        /// </summary>
        public static string MsgErrorFirstName {
            get {
                return ResourceManager.GetString("MsgErrorFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Userbild konnte nicht gespeichert werden!.
        /// </summary>
        public static string MsgErrorImage {
            get {
                return ResourceManager.GetString("MsgErrorImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nachname nicht gesetzt!.
        /// </summary>
        public static string MsgErrorLastName {
            get {
                return ResourceManager.GetString("MsgErrorLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwort ungültig!.
        /// </summary>
        public static string MsgErrorPassword {
            get {
                return ResourceManager.GetString("MsgErrorPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefonnummer nicht gesetzt!.
        /// </summary>
        public static string MsgErrorPhone {
            get {
                return ResourceManager.GetString("MsgErrorPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemeinde nicht ausgewählt!.
        /// </summary>
        public static string MsgErrorTown {
            get {
                return ResourceManager.GetString("MsgErrorTown", resourceCulture);
            }
        }
    }
}
