//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResViewOrganization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResViewOrganization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResViewOrganization", typeof(ResViewOrganization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation hinzufügen.
        /// </summary>
        public static string CmdAddOrganization {
            get {
                return ResourceManager.GetString("CmdAddOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User hinzufügen.
        /// </summary>
        public static string CmdAddUser {
            get {
                return ResourceManager.GetString("CmdAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string CmdDeleteOrganization {
            get {
                return ResourceManager.GetString("CmdDeleteOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löschen.
        /// </summary>
        public static string CmdDeleteUser {
            get {
                return ResourceManager.GetString("CmdDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        public static string CmdEditOrganization {
            get {
                return ResourceManager.GetString("CmdEditOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearbeiten.
        /// </summary>
        public static string CmdEditUser {
            get {
                return ResourceManager.GetString("CmdEditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daten neu laden (Test).
        /// </summary>
        public static string CmdReloadOrganizations {
            get {
                return ResourceManager.GetString("CmdReloadOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuelle Ideen.
        /// </summary>
        public static string LblCurrentIdeas {
            get {
                return ResourceManager.GetString("LblCurrentIdeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktuelle Organisationen.
        /// </summary>
        public static string LblCurrentOrganizations {
            get {
                return ResourceManager.GetString("LblCurrentOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to aktuelle(r) Benutzer.
        /// </summary>
        public static string LblCurrentUsers {
            get {
                return ResourceManager.GetString("LblCurrentUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Ideen.
        /// </summary>
        public static string LblNoIdeas {
            get {
                return ResourceManager.GetString("LblNoIdeas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Organisationen.
        /// </summary>
        public static string LblNoOrganizations {
            get {
                return ResourceManager.GetString("LblNoOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisation.
        /// </summary>
        public static string LblOrganization {
            get {
                return ResourceManager.GetString("LblOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwaltung meiner Gemeinden.
        /// </summary>
        public static string LblSubTitle {
            get {
                return ResourceManager.GetString("LblSubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemeinden.
        /// </summary>
        public static string LblTitle {
            get {
                return ResourceManager.GetString("LblTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User der Organisation.
        /// </summary>
        public static string LblUsers {
            get {
                return ResourceManager.GetString("LblUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sicher, dass du den User aus der aktuellen Gemeinde entfernen willst?.
        /// </summary>
        public static string MsgConfirmUserDelete {
            get {
                return ResourceManager.GetString("MsgConfirmUserDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User entfernen.
        /// </summary>
        public static string MsgConfirmUserDeleteTitle {
            get {
                return ResourceManager.GetString("MsgConfirmUserDeleteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Löchen leider nicht möglich..
        /// </summary>
        public static string MsgDeleteError {
            get {
                return ResourceManager.GetString("MsgDeleteError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Organisation kann nicht gelöscht werden..
        /// </summary>
        public static string MsgDeleteOrganizationNotPossible {
            get {
                return ResourceManager.GetString("MsgDeleteOrganizationNotPossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diese Organisation kann nicht bearbeitet werden..
        /// </summary>
        public static string MsgEditOrganizationNotPossible {
            get {
                return ResourceManager.GetString("MsgEditOrganizationNotPossible", resourceCulture);
            }
        }
    }
}
