//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exchange.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResWebCommon {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResWebCommon() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Exchange.Resources.ResWebCommon", typeof(ResWebCommon).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Nachricht in Chat {0}.
        /// </summary>
        public static string PushChatTitle {
            get {
                return ResourceManager.GetString("PushChatTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jemanden gefällt deine Idee.
        /// </summary>
        public static string PushIdeaLikeMessage {
            get {
                return ResourceManager.GetString("PushIdeaLikeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like!.
        /// </summary>
        public static string PushIdeaLikeTitle {
            get {
                return ResourceManager.GetString("PushIdeaLikeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eine neue Idee ist verfügbar.
        /// </summary>
        public static string PushNewIdeaMessage {
            get {
                return ResourceManager.GetString("PushNewIdeaMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neue Idee!.
        /// </summary>
        public static string PushNewIdeaTitle {
            get {
                return ResourceManager.GetString("PushNewIdeaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jemand hat eine Idee gemeldet.
        /// </summary>
        public static string PushNewReportMessage {
            get {
                return ResourceManager.GetString("PushNewReportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meldung!.
        /// </summary>
        public static string PushNewReportTitle {
            get {
                return ResourceManager.GetString("PushNewReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jemand unterstützt deine Idee.
        /// </summary>
        public static string PushNewSupportMessage {
            get {
                return ResourceManager.GetString("PushNewSupportMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unterstützung!.
        /// </summary>
        public static string PushNewSupportTitle {
            get {
                return ResourceManager.GetString("PushNewSupportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um deine Registrierung abzuschließen, gibt diesen Code in der App ein: .
        /// </summary>
        public static string SmsRegistration {
            get {
                return ResourceManager.GetString("SmsRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LENIE - Wöchentliche Auswertung.
        /// </summary>
        public static string WeeklyReportTitle {
            get {
                return ResourceManager.GetString("WeeklyReportTitle", resourceCulture);
            }
        }
    }
}
